import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, resolve } from 'node:path';
import {
  buildInstrumentUniverseSnapshotMetadata,
  summarizeInstrumentUniverse,
  validateInstrumentUniverseJson,
} from '../src/domain/instrumentUniverse';

const TARGET_FILE = resolve(process.cwd(), 'src/data/instrumentUniverseBundled.ts');

const usage = () => {
  console.error('Usage: npm -w apps/midas run instrument-universe:update-bundled -- [--dry-run] <official-instrument-universe-v1.json>');
};

const escapeForTsString = (value: string) =>
  value
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');

const args = process.argv.slice(2);
const dryRun = args.includes('--dry-run');
const helpRequested = args.includes('--help') || args.includes('-h');
const inputPath = args.find((arg) => !arg.startsWith('--'));

if (helpRequested) {
  usage();
  process.exit(0);
}

if (!inputPath) {
  usage();
  process.exit(1);
}

const absoluteInputPath = resolve(process.cwd(), inputPath);
const rawJson = readFileSync(absoluteInputPath, 'utf8');
const validation = validateInstrumentUniverseJson(rawJson);

if (!validation.ok || !validation.snapshot) {
  console.error('Instrument Universe V1 backup was not updated: source JSON is invalid.');
  validation.errors.forEach((error) => console.error(`- ${error}`));
  validation.warnings.forEach((warning) => console.error(`- warning: ${warning}`));
  process.exit(1);
}

const savedAt = new Date().toISOString();
const snapshot = { ...validation.snapshot, savedAt };
const summary = summarizeInstrumentUniverse(snapshot);
const metadata = buildInstrumentUniverseSnapshotMetadata(snapshot, validation, {
  fileName: basename(absoluteInputPath),
  source: 'bundled',
  loadedAt: savedAt,
});

const blockingErrors = [
  Math.abs(metadata.totalWeightPortfolio - 1) > 0.03
    ? `total weight must be close to 100%; received ${metadata.totalWeightPortfolio}`
    : null,
  metadata.instrumentsCount <= 0 ? 'source must include instruments' : null,
  metadata.validInstrumentsCount <= 0 ? 'source must include usable instruments' : null,
  !metadata.hasUsableAmounts ? 'source must include usable amount_clp values' : null,
  !metadata.hasUsableWeights ? 'source must include usable weight_portfolio values' : null,
  !metadata.hasUsableMix ? 'source must include current_mix_used values' : null,
].filter((item): item is string => !!item);

if (blockingErrors.length > 0) {
  console.error('Instrument Universe V1 backup was not updated: source JSON failed backup policy.');
  blockingErrors.forEach((error) => console.error(`- ${error}`));
  process.exit(1);
}

const output = `// Generated by scripts/updateInstrumentUniverseBundled.ts.
// Review and commit this file only after the source JSON is approved as official Instrument Universe V1.
export const BUNDLED_INSTRUMENT_UNIVERSE_FILE_NAME = ${JSON.stringify(basename(absoluteInputPath))};
export const BUNDLED_INSTRUMENT_UNIVERSE_SAVED_AT = ${JSON.stringify(savedAt)};
export const BUNDLED_INSTRUMENT_UNIVERSE_RAW = \`${escapeForTsString(rawJson.trim())}\`;
`;

mkdirSync(dirname(TARGET_FILE), { recursive: true });
if (!dryRun) {
  writeFileSync(TARGET_FILE, output, 'utf8');
}

console.log(dryRun ? 'Instrument Universe V1 bundled backup validated (dry-run).' : 'Instrument Universe V1 bundled backup updated.');
console.log(`source_file=${absoluteInputPath}`);
console.log(`target_file=${TARGET_FILE}`);
console.log(`checksum=${metadata.checksum}`);
console.log(`schema_version=${metadata.schemaVersion}`);
console.log(`instruments=${metadata.instrumentsCount}`);
console.log(`usable_instruments=${metadata.validInstrumentsCount}`);
console.log(`total_portfolio_clp=${metadata.totalAmountClp}`);
console.log(`total_weight=${metadata.totalWeightPortfolio}`);
if (summary?.currentMix) {
  console.log(`mix_rv=${summary.currentMix.rv}`);
  console.log(`mix_rf=${summary.currentMix.rf}`);
  console.log(`mix_cash=${summary.currentMix.cash}`);
  console.log(`mix_other=${summary.currentMix.other}`);
}
