// Generated by scripts/updateInstrumentUniverseBundled.ts.
// Review and commit this file only after the source JSON is approved as official Instrument Universe V1.
export const BUNDLED_INSTRUMENT_UNIVERSE_FILE_NAME = "instrument_universe_post_fase_1.json";
export const BUNDLED_INSTRUMENT_UNIVERSE_SAVED_AT = "2026-07-07T01:02:44.429Z";
export const BUNDLED_INSTRUMENT_UNIVERSE_RAW = `{
  "schema_version": "1.1",
  "portfolio_id": "diego_core_portfolio",
  "as_of_date": "2026-07-06",
  "base_currency": "CLP",
  "usd_fx_to_clp_used": 921.74,
  "total_portfolio_clp": 1552431942,
  "methodology": {
    "purpose": "Determine whether target RV/RF mix is reachable with current instruments or requires structural changes.",
    "current_mix_method": "sum(weight_portfolio * current_mix_used)",
    "historical_band_method": "sum(weight_portfolio * historical_used_range)",
    "notes": [
      "tax_wrapper left null/manual by user instruction",
      "BTG Activa and BTG Agresiva historical_used_range are prudent estimates, not full look-through history",
      "SURA Moderado legal_range is ambiguous in available docs; optimizer_safe_range is used operationally",
      "Post-Fase 1 rebalance July 2026: SURA Moderado set to zero; SURA Agresivo/Renta Local UF increased; BTG Activa reduced; BTG Agresiva/Conservadora increased.",
      "Aurum remains the canonical source for economic capital; this universe defines structural weights and RV/RF composition."
    ]
  },
  "portfolio_summary": {
    "current_mix": {
      "rv": 0.611549678,
      "rf": 0.384396232,
      "cash": 0.002437945,
      "other": 0.001616144
    },
    "historical_used_range": {
      "rv_min": 0.590360391,
      "rv_max": 0.624225249,
      "rf_min": 0.374022337,
      "rf_max": 0.409639609
    },
    "decision_thresholds": {
      "requires_structural_change_if_target_rv_below": 0.590360391,
      "requires_structural_change_if_target_rv_above": 0.624225249
    }
  },
  "instruments": [
    {
      "instrument_master": {
        "instrument_id": "sura_multiactivo_agresivo",
        "name": "SURA Multiactivo Agresivo",
        "manager": "SURA",
        "series": "I",
        "vehicle_type": "fondo_mutuo",
        "currency": "CLP",
        "tax_wrapper": null,
        "liquidity_days": 10,
        "is_captive": false,
        "is_sellable": true,
        "can_switch_internal": true,
        "partial_redeemable": true,
        "minimum_trade_amount_clp": 700000000,
        "minimum_residual_amount_clp": 5000
      },
      "instrument_mix_profile": {
        "reported_current_mix": {
          "rv": 0.8617,
          "rf": 0.1383,
          "cash": 0.0,
          "other": 0.0
        },
        "estimated_current_mix": null,
        "current_mix_used": {
          "rv": 0.8617,
          "rf": 0.1383,
          "cash": 0.0,
          "other": 0.0,
          "source_preference": "reported"
        },
        "reported_current_exposure": {
          "global": 0.809,
          "local": 0.191,
          "hedged": null,
          "unhedged": null
        },
        "estimated_current_exposure": null,
        "current_exposure_used": {
          "global": 0.809,
          "local": 0.191,
          "hedged": null,
          "unhedged": null,
          "source_preference": "reported"
        },
        "legal_range": {
          "rv_min": 0.6,
          "rv_max": 1.0,
          "rf_min": 0.0,
          "rf_max": 0.4,
          "cash_min": 0.0,
          "cash_max": 0.1
        },
        "historical_used_range": {
          "rv_min": 0.848,
          "rv_max": 0.88,
          "rf_min": 0.12,
          "rf_max": 0.152,
          "observed_window_months": 12,
          "observed_from": "2025-01-31",
          "observed_to": "2026-01-31",
          "observation_count": 4,
          "estimation_method": "manager_report"
        },
        "data_quality": {
          "range_source_type": "manager_report",
          "lookthrough_quality": "high",
          "confidence_score": 0.9,
          "current_mix_quality": "high",
          "historical_range_quality": "high",
          "current_exposure_quality": "high"
        },
        "source_metadata": {
          "current_mix_source": "SURA ficha enero 2026",
          "historical_range_source": "SURA manager report 1m/3m/12m",
          "legal_range_source": "SURA folleto/CMF",
          "current_exposure_source": "SURA ficha enero 2026",
          "last_verified_at": "2026-04-16"
        }
      },
      "portfolio_position": {
        "amount_native": 726208327,
        "amount_native_currency": "CLP",
        "fx_to_clp_used": 1.0,
        "valuation_date": "2026-07-06",
        "amount_clp": 726208327,
        "weight_portfolio": 0.467787545,
        "role": "growth",
        "core_or_satellite": "core",
        "bucket_eligible": false,
        "structural_mix_driver": true,
        "estimated_mix_impact_points": {
          "current_rv_points": 0.403092528,
          "historical_rv_points_min": 0.396683838,
          "historical_rv_points_max": 0.41165304
        }
      },
      "optimizer_metadata": {
        "replaceability_score": 0.7,
        "replacement_constraint": "medium",
        "switch_equivalent_candidates": [
          "sura_multiactivo_moderado",
          "btg_gestion_agresiva",
          "btg_gestion_activa"
        ],
        "same_currency_candidates": [
          "sura_multiactivo_moderado",
          "btg_gestion_agresiva",
          "btg_gestion_activa"
        ],
        "same_manager_candidates": [
          "sura_multiactivo_moderado",
          "sura_renta_bonos_chile",
          "sura_renta_local_uf"
        ],
        "same_tax_wrapper_candidates": [],
        "decision_eligible": true,
        "notes": [
          "Serie I: TAC 1.45%, remuneraciÃ³n mÃ¡xima 1.70% IVA incluido, 57/107/108 LIR disponible en folleto.",
          "Post-Fase 1: monto consolidado mantiene la estructura actual del universe y refleja aumento por salida de SURA Moderado."
        ]
      }
    },
    {
      "instrument_master": {
        "instrument_id": "sura_multiactivo_moderado",
        "name": "SURA Multiactivo Moderado",
        "manager": "SURA",
        "series": "I",
        "vehicle_type": "fondo_mutuo",
        "currency": "CLP",
        "tax_wrapper": null,
        "liquidity_days": 10,
        "is_captive": false,
        "is_sellable": true,
        "can_switch_internal": true,
        "partial_redeemable": true,
        "minimum_trade_amount_clp": 700000000,
        "minimum_residual_amount_clp": 5000
      },
      "instrument_mix_profile": {
        "reported_current_mix": {
          "rv": 0.5177,
          "rf": 0.4823,
          "cash": 0.0,
          "other": 0.0
        },
        "estimated_current_mix": null,
        "current_mix_used": {
          "rv": 0.5177,
          "rf": 0.4823,
          "cash": 0.0,
          "other": 0.0,
          "source_preference": "reported"
        },
        "reported_current_exposure": {
          "global": 0.5992,
          "local": 0.4008,
          "hedged": null,
          "unhedged": null
        },
        "estimated_current_exposure": null,
        "current_exposure_used": {
          "global": 0.5992,
          "local": 0.4008,
          "hedged": null,
          "unhedged": null,
          "source_preference": "reported"
        },
        "legal_range": {
          "rv_min": 0.0,
          "rv_max": 1.0,
          "rf_min": 0.0,
          "rf_max": 1.0,
          "cash_min": 0.0,
          "cash_max": 0.2
        },
        "optimizer_safe_range": {
          "rv_min": 0.45,
          "rv_max": 0.6,
          "rf_min": 0.4,
          "rf_max": 0.55
        },
        "historical_used_range": {
          "rv_min": 0.515,
          "rv_max": 0.564,
          "rf_min": 0.436,
          "rf_max": 0.483,
          "observed_window_months": 12,
          "observed_from": "2025-02-28",
          "observed_to": "2026-02-28",
          "observation_count": 4,
          "estimation_method": "manager_report"
        },
        "data_quality": {
          "range_source_type": "manager_report",
          "lookthrough_quality": "high",
          "confidence_score": 0.86,
          "current_mix_quality": "high",
          "historical_range_quality": "high",
          "current_exposure_quality": "high",
          "legal_range_quality": "low"
        },
        "source_metadata": {
          "current_mix_source": "SURA ficha febrero 2026",
          "historical_range_source": "SURA manager report 1m/3m/12m",
          "legal_range_source": "SURA folleto disponible; banda explÃ­cita insuficiente",
          "current_exposure_source": "SURA ficha febrero 2026",
          "last_verified_at": "2026-04-16"
        }
      },
      "portfolio_position": {
        "amount_native": 0,
        "amount_native_currency": "CLP",
        "fx_to_clp_used": 1.0,
        "valuation_date": "2026-07-06",
        "amount_clp": 0,
        "weight_portfolio": 0.0,
        "role": "bridge",
        "core_or_satellite": "satellite",
        "bucket_eligible": false,
        "structural_mix_driver": false,
        "estimated_mix_impact_points": {
          "current_rv_points": 0.0,
          "historical_rv_points_min": 0.0,
          "historical_rv_points_max": 0.0
        }
      },
      "optimizer_metadata": {
        "replaceability_score": 0.8,
        "replacement_constraint": "low",
        "switch_equivalent_candidates": [
          "sura_multiactivo_agresivo",
          "btg_gestion_activa"
        ],
        "same_currency_candidates": [
          "sura_multiactivo_agresivo",
          "btg_gestion_activa"
        ],
        "same_manager_candidates": [
          "sura_multiactivo_agresivo",
          "sura_renta_bonos_chile",
          "sura_renta_local_uf"
        ],
        "same_tax_wrapper_candidates": [],
        "decision_eligible": true,
        "notes": [
          "Serie I: TAC 1.47%, remuneraciÃ³n mÃ¡xima 1.50% IVA incluido, 57/107/108 LIR disponible en folleto.",
          "legal_range operativo se trata con optimizer_safe_range por ambigÃ¼edad regulatoria en la banda exacta.",
          "Post-Fase 1: posiciÃ³n cerrada; se mantiene instrumento en cero para trazabilidad y compatibilidad de schema."
        ]
      }
    },
    {
      "instrument_master": {
        "instrument_id": "sura_renta_bonos_chile",
        "name": "SURA Renta Bonos Chile",
        "manager": "SURA",
        "series": null,
        "vehicle_type": "fondo_mutuo",
        "currency": "CLP",
        "tax_wrapper": null,
        "liquidity_days": 10,
        "is_captive": false,
        "is_sellable": true,
        "can_switch_internal": true,
        "partial_redeemable": true,
        "minimum_trade_amount_clp": null,
        "minimum_residual_amount_clp": null
      },
      "instrument_mix_profile": {
        "reported_current_mix": {
          "rv": 0.0,
          "rf": 0.9979,
          "cash": 0.0,
          "other": 0.0021
        },
        "estimated_current_mix": null,
        "current_mix_used": {
          "rv": 0.0,
          "rf": 0.9979,
          "cash": 0.0,
          "other": 0.0021,
          "source_preference": "reported"
        },
        "reported_current_exposure": {
          "global": 0.0,
          "local": 1.0,
          "hedged": null,
          "unhedged": null
        },
        "estimated_current_exposure": null,
        "current_exposure_used": {
          "global": 0.0,
          "local": 1.0,
          "hedged": null,
          "unhedged": null,
          "source_preference": "reported"
        },
        "legal_range": {
          "rv_min": 0.0,
          "rv_max": 0.05,
          "rf_min": 0.95,
          "rf_max": 1.0,
          "cash_min": 0.0,
          "cash_max": 0.05
        },
        "historical_used_range": {
          "rv_min": 0.0,
          "rv_max": 0.005,
          "rf_min": 0.995,
          "rf_max": 1.0,
          "observed_window_months": 12,
          "observed_from": "2025-01-01",
          "observed_to": "2025-12-31",
          "observation_count": 1,
          "estimation_method": "reported_lookthrough"
        },
        "data_quality": {
          "range_source_type": "reported_lookthrough",
          "lookthrough_quality": "high",
          "confidence_score": 0.9,
          "current_mix_quality": "high",
          "historical_range_quality": "medium",
          "current_exposure_quality": "high"
        },
        "source_metadata": {
          "current_mix_source": "SURA ficha/fondo deuda",
          "historical_range_source": "operational_assumption_from_debt_fund_type",
          "legal_range_source": "fund type + prudent optimizer assumption",
          "current_exposure_source": "fund type local debt",
          "last_verified_at": "2026-04-16"
        }
      },
      "portfolio_position": {
        "amount_native": 69144140,
        "amount_native_currency": "CLP",
        "fx_to_clp_used": 1.0,
        "valuation_date": "2026-07-06",
        "amount_clp": 69144140,
        "weight_portfolio": 0.044539241,
        "role": "defensive",
        "core_or_satellite": "core",
        "bucket_eligible": true,
        "structural_mix_driver": true,
        "estimated_mix_impact_points": {
          "current_rv_points": 0.0,
          "historical_rv_points_min": 0.0,
          "historical_rv_points_max": 0.000222696
        }
      },
      "optimizer_metadata": {
        "replaceability_score": 0.85,
        "replacement_constraint": "low",
        "switch_equivalent_candidates": [
          "sura_renta_local_uf",
          "btg_gestion_conservadora",
          "sura_money_market_usd"
        ],
        "same_currency_candidates": [
          "sura_renta_local_uf",
          "btg_gestion_conservadora"
        ],
        "same_manager_candidates": [
          "sura_renta_local_uf",
          "sura_multiactivo_moderado"
        ],
        "same_tax_wrapper_candidates": [],
        "decision_eligible": true,
        "notes": []
      }
    },
    {
      "instrument_master": {
        "instrument_id": "sura_renta_local_uf",
        "name": "SURA Renta Local UF",
        "manager": "SURA",
        "series": null,
        "vehicle_type": "fondo_mutuo",
        "currency": "CLP",
        "tax_wrapper": null,
        "liquidity_days": 10,
        "is_captive": false,
        "is_sellable": true,
        "can_switch_internal": true,
        "partial_redeemable": true,
        "minimum_trade_amount_clp": null,
        "minimum_residual_amount_clp": null
      },
      "instrument_mix_profile": {
        "reported_current_mix": {
          "rv": 0.0,
          "rf": 0.992,
          "cash": 0.0,
          "other": 0.008
        },
        "estimated_current_mix": null,
        "current_mix_used": {
          "rv": 0.0,
          "rf": 0.992,
          "cash": 0.0,
          "other": 0.008,
          "source_preference": "reported"
        },
        "reported_current_exposure": {
          "global": 0.0,
          "local": 1.0,
          "hedged": null,
          "unhedged": null
        },
        "estimated_current_exposure": null,
        "current_exposure_used": {
          "global": 0.0,
          "local": 1.0,
          "hedged": null,
          "unhedged": null,
          "source_preference": "reported"
        },
        "legal_range": {
          "rv_min": 0.0,
          "rv_max": 0.05,
          "rf_min": 0.95,
          "rf_max": 1.0,
          "cash_min": 0.0,
          "cash_max": 0.05
        },
        "historical_used_range": {
          "rv_min": 0.0,
          "rv_max": 0.008,
          "rf_min": 0.992,
          "rf_max": 1.0,
          "observed_window_months": 12,
          "observed_from": "2025-01-01",
          "observed_to": "2025-12-31",
          "observation_count": 1,
          "estimation_method": "reported_lookthrough"
        },
        "data_quality": {
          "range_source_type": "reported_lookthrough",
          "lookthrough_quality": "high",
          "confidence_score": 0.88,
          "current_mix_quality": "high",
          "historical_range_quality": "medium",
          "current_exposure_quality": "high"
        },
        "source_metadata": {
          "current_mix_source": "SURA ficha/fondo deuda UF",
          "historical_range_source": "operational_assumption_from_debt_fund_type",
          "legal_range_source": "fund type + prudent optimizer assumption",
          "current_exposure_source": "fund type local debt",
          "last_verified_at": "2026-04-16"
        }
      },
      "portfolio_position": {
        "amount_native": 57572970,
        "amount_native_currency": "CLP",
        "fx_to_clp_used": 1.0,
        "valuation_date": "2026-07-06",
        "amount_clp": 57572970,
        "weight_portfolio": 0.037085664,
        "role": "defensive",
        "core_or_satellite": "core",
        "bucket_eligible": true,
        "structural_mix_driver": false,
        "estimated_mix_impact_points": {
          "current_rv_points": 0.0,
          "historical_rv_points_min": 0.0,
          "historical_rv_points_max": 0.000296685
        }
      },
      "optimizer_metadata": {
        "replaceability_score": 0.82,
        "replacement_constraint": "low",
        "switch_equivalent_candidates": [
          "sura_renta_bonos_chile",
          "btg_gestion_conservadora"
        ],
        "same_currency_candidates": [
          "sura_renta_bonos_chile",
          "btg_gestion_conservadora"
        ],
        "same_manager_candidates": [
          "sura_renta_bonos_chile",
          "sura_multiactivo_moderado"
        ],
        "same_tax_wrapper_candidates": [],
        "decision_eligible": true,
        "notes": [
          "Post-Fase 1: aumentado por traspaso desde SURA Moderado."
        ]
      }
    },
    {
      "instrument_master": {
        "instrument_id": "btg_gestion_activa",
        "name": "BTG Pactual GestiÃ³n Activa",
        "manager": "BTG Pactual",
        "series": "I",
        "vehicle_type": "fondo_mutuo",
        "currency": "CLP",
        "tax_wrapper": null,
        "liquidity_days": 10,
        "is_captive": false,
        "is_sellable": true,
        "can_switch_internal": true,
        "partial_redeemable": true,
        "minimum_trade_amount_clp": 200000000,
        "minimum_residual_amount_clp": null
      },
      "instrument_mix_profile": {
        "reported_current_mix": {
          "rv": 0.4835,
          "rf": 0.5165,
          "cash": 0.0,
          "other": 0.0
        },
        "estimated_current_mix": null,
        "current_mix_used": {
          "rv": 0.4835,
          "rf": 0.5165,
          "cash": 0.0,
          "other": 0.0,
          "source_preference": "reported"
        },
        "reported_current_exposure": {
          "global": 0.4193,
          "local": 0.5807,
          "hedged": null,
          "unhedged": null
        },
        "estimated_current_exposure": null,
        "current_exposure_used": {
          "global": 0.4193,
          "local": 0.5807,
          "hedged": null,
          "unhedged": null,
          "source_preference": "reported"
        },
        "legal_range": {
          "rv_min": 0.0,
          "rv_max": 0.7,
          "rf_min": 0.3,
          "rf_max": 1.0,
          "cash_min": 0.0,
          "cash_max": 0.2
        },
        "optimizer_safe_range": {
          "rv_min": 0.0,
          "rv_max": 0.6,
          "rf_min": 0.4,
          "rf_max": 1.0
        },
        "historical_used_range": {
          "rv_min": 0.44,
          "rv_max": 0.5,
          "rf_min": 0.5,
          "rf_max": 0.56,
          "observed_window_months": 29,
          "observed_from": "2023-09-30",
          "observed_to": "2026-02-28",
          "observation_count": 4,
          "estimation_method": "proxy_capitalizacion_adjusted"
        },
        "data_quality": {
          "range_source_type": "proxy_capitalizacion_adjusted",
          "lookthrough_quality": "medium",
          "confidence_score": 0.7,
          "current_mix_quality": "high",
          "historical_range_quality": "medium",
          "current_exposure_quality": "medium",
          "legal_range_quality": "medium"
        },
        "source_metadata": {
          "current_mix_source": "BTG factsheet febrero 2026",
          "historical_range_source": "BTG carteras trimestrales 2023-2025 + prudential adjustment",
          "legal_range_source": "CMF 70% + BTG website 60% conflict",
          "current_exposure_source": "BTG factsheet febrero 2026",
          "last_verified_at": "2026-04-16"
        }
      },
      "portfolio_position": {
        "amount_native": 44128982,
        "amount_native_currency": "CLP",
        "fx_to_clp_used": 1.0,
        "valuation_date": "2026-07-06",
        "amount_clp": 44128982,
        "weight_portfolio": 0.028425711,
        "role": "bridge",
        "core_or_satellite": "core",
        "bucket_eligible": false,
        "structural_mix_driver": true,
        "estimated_mix_impact_points": {
          "current_rv_points": 0.013743831,
          "historical_rv_points_min": 0.012507313,
          "historical_rv_points_max": 0.014212856
        }
      },
      "optimizer_metadata": {
        "replaceability_score": 0.75,
        "replacement_constraint": "low",
        "switch_equivalent_candidates": [
          "sura_multiactivo_moderado",
          "sura_multiactivo_agresivo",
          "btg_gestion_conservadora"
        ],
        "same_currency_candidates": [
          "sura_multiactivo_moderado",
          "sura_multiactivo_agresivo",
          "btg_gestion_conservadora"
        ],
        "same_manager_candidates": [
          "btg_gestion_conservadora",
          "btg_gestion_agresiva"
        ],
        "same_tax_wrapper_candidates": [],
        "decision_eligible": true,
        "notes": [
          "Conflicto legal vigente: CMF permite 70% capitalizaciÃ³n; web BTG muestra 60%. MIDAS usa optimizer_safe_range 60%.",
          "Serie I: fee fija mÃ¡x 0.90% y fee variable 15% sobre exceso vs 4% UF anual, sin comisiÃ³n de rescate.",
          "Post-Fase 1: reducido parcialmente y se mantiene remanente por diversificaciÃ³n de manager/escenarios."
        ]
      }
    },
    {
      "instrument_master": {
        "instrument_id": "btg_gestion_conservadora",
        "name": "BTG Pactual GestiÃ³n Conservadora",
        "manager": "BTG Pactual",
        "series": "I",
        "vehicle_type": "fondo_mutuo",
        "currency": "CLP",
        "tax_wrapper": null,
        "liquidity_days": 10,
        "is_captive": false,
        "is_sellable": true,
        "can_switch_internal": true,
        "partial_redeemable": true,
        "minimum_trade_amount_clp": 200000000,
        "minimum_residual_amount_clp": null
      },
      "instrument_mix_profile": {
        "reported_current_mix": {
          "rv": 0.1884,
          "rf": 0.7953,
          "cash": 0.012,
          "other": 0.0043
        },
        "estimated_current_mix": null,
        "current_mix_used": {
          "rv": 0.1884,
          "rf": 0.7953,
          "cash": 0.012,
          "other": 0.0043,
          "source_preference": "reported"
        },
        "reported_current_exposure": {
          "global": 0.387146,
          "local": 0.612854,
          "hedged": null,
          "unhedged": null
        },
        "estimated_current_exposure": null,
        "current_exposure_used": {
          "global": 0.387146,
          "local": 0.612854,
          "hedged": null,
          "unhedged": null,
          "source_preference": "reported"
        },
        "legal_range": {
          "rv_min": 0.0,
          "rv_max": 0.2,
          "rf_min": 0.8,
          "rf_max": 1.0,
          "cash_min": 0.0,
          "cash_max": 0.1
        },
        "historical_used_range": {
          "rv_min": 0.16,
          "rv_max": 0.2,
          "rf_min": 0.8,
          "rf_max": 0.84,
          "observed_window_months": 11,
          "observed_from": "2025-03-31",
          "observed_to": "2026-02-28",
          "observation_count": 3,
          "estimation_method": "reported_current_plus_legal_floor"
        },
        "data_quality": {
          "range_source_type": "reported_current_plus_legal_floor",
          "lookthrough_quality": "medium",
          "confidence_score": 0.82,
          "current_mix_quality": "high",
          "historical_range_quality": "medium",
          "current_exposure_quality": "medium",
          "legal_range_quality": "high"
        },
        "source_metadata": {
          "current_mix_source": "BTG factsheet febrero 2026",
          "historical_range_source": "BTG carteras 2025 + debt floor",
          "legal_range_source": "Reglamento/CMF debt floor 80%",
          "current_exposure_source": "BTG factsheet febrero 2026",
          "last_verified_at": "2026-04-16"
        }
      },
      "portfolio_position": {
        "amount_native": 149119789,
        "amount_native_currency": "CLP",
        "fx_to_clp_used": 1.0,
        "valuation_date": "2026-07-06",
        "amount_clp": 149119789,
        "weight_portfolio": 0.096055605,
        "role": "defensive",
        "core_or_satellite": "core",
        "bucket_eligible": true,
        "structural_mix_driver": true,
        "estimated_mix_impact_points": {
          "current_rv_points": 0.018096876,
          "historical_rv_points_min": 0.015368897,
          "historical_rv_points_max": 0.019211121
        }
      },
      "optimizer_metadata": {
        "replaceability_score": 0.88,
        "replacement_constraint": "low",
        "switch_equivalent_candidates": [
          "sura_renta_bonos_chile",
          "sura_renta_local_uf",
          "btg_gestion_activa"
        ],
        "same_currency_candidates": [
          "sura_renta_bonos_chile",
          "sura_renta_local_uf",
          "btg_gestion_activa"
        ],
        "same_manager_candidates": [
          "btg_gestion_activa",
          "btg_gestion_agresiva"
        ],
        "same_tax_wrapper_candidates": [],
        "decision_eligible": true,
        "notes": [
          "Serie I: fee fija mÃ¡x 0.90%, fee variable 15% sobre exceso vs 3% UF anual, sin comisiÃ³n de rescate.",
          "Post-Fase 1: aumentado por traspaso parcial desde BTG GestiÃ³n Activa."
        ]
      }
    },
    {
      "instrument_master": {
        "instrument_id": "btg_gestion_agresiva",
        "name": "BTG Pactual GestiÃ³n Agresiva",
        "manager": "BTG Pactual",
        "series": "I",
        "vehicle_type": "fondo_mutuo",
        "currency": "CLP",
        "tax_wrapper": null,
        "liquidity_days": 10,
        "is_captive": false,
        "is_sellable": true,
        "can_switch_internal": true,
        "partial_redeemable": true,
        "minimum_trade_amount_clp": 200000000,
        "minimum_residual_amount_clp": null
      },
      "instrument_mix_profile": {
        "reported_current_mix": {
          "rv": 0.7207,
          "rf": 0.2388,
          "cash": 0.0251,
          "other": 0.0154
        },
        "estimated_current_mix": null,
        "current_mix_used": {
          "rv": 0.7207,
          "rf": 0.2388,
          "cash": 0.0251,
          "other": 0.0154,
          "source_preference": "reported"
        },
        "reported_current_exposure": {
          "global": 0.599036,
          "local": 0.400964,
          "hedged": null,
          "unhedged": null
        },
        "estimated_current_exposure": null,
        "current_exposure_used": {
          "global": 0.599036,
          "local": 0.400964,
          "hedged": null,
          "unhedged": null,
          "source_preference": "reported"
        },
        "legal_range": {
          "rv_min": 0.0,
          "rv_max": 0.9,
          "rf_min": 0.1,
          "rf_max": 1.0,
          "cash_min": 0.0,
          "cash_max": 0.2
        },
        "historical_used_range": {
          "rv_min": 0.68,
          "rv_max": 0.76,
          "rf_min": 0.24,
          "rf_max": 0.32,
          "observed_window_months": 17,
          "observed_from": "2024-09-30",
          "observed_to": "2026-02-28",
          "observation_count": 3,
          "estimation_method": "proxy_capitalizacion_adjusted"
        },
        "data_quality": {
          "range_source_type": "proxy_capitalizacion_adjusted",
          "lookthrough_quality": "medium",
          "confidence_score": 0.74,
          "current_mix_quality": "high",
          "historical_range_quality": "medium",
          "current_exposure_quality": "medium",
          "legal_range_quality": "high"
        },
        "source_metadata": {
          "current_mix_source": "BTG factsheet febrero 2026",
          "historical_range_source": "BTG carteras 2024-2025 + prudential adjustment",
          "legal_range_source": "BTG website/CMF 90% capitalizaciÃ³n",
          "current_exposure_source": "BTG factsheet febrero 2026",
          "last_verified_at": "2026-04-16"
        }
      },
      "portfolio_position": {
        "amount_native": 79494295,
        "amount_native_currency": "CLP",
        "fx_to_clp_used": 1.0,
        "valuation_date": "2026-07-06",
        "amount_clp": 79494295,
        "weight_portfolio": 0.0512063,
        "role": "growth",
        "core_or_satellite": "satellite",
        "bucket_eligible": false,
        "structural_mix_driver": false,
        "estimated_mix_impact_points": {
          "current_rv_points": 0.03690438,
          "historical_rv_points_min": 0.034820284,
          "historical_rv_points_max": 0.038916788
        }
      },
      "optimizer_metadata": {
        "replaceability_score": 0.92,
        "replacement_constraint": "low",
        "switch_equivalent_candidates": [
          "sura_multiactivo_agresivo",
          "btg_gestion_activa"
        ],
        "same_currency_candidates": [
          "sura_multiactivo_agresivo",
          "btg_gestion_activa"
        ],
        "same_manager_candidates": [
          "btg_gestion_activa",
          "btg_gestion_conservadora"
        ],
        "same_tax_wrapper_candidates": [],
        "decision_eligible": true,
        "notes": [
          "Serie I: TAC 2.76%, fee fija mÃ¡x 1.3280%, fee variable 15% sobre exceso vs 5% UF anual, sin comisiÃ³n de rescate.",
          "Post-Fase 1: aumentado por traspaso parcial desde BTG GestiÃ³n Activa."
        ]
      }
    },
    {
      "instrument_master": {
        "instrument_id": "planvital_fondo_a",
        "name": "AFP PlanVital Fondo A",
        "manager": "AFP PlanVital",
        "series": null,
        "vehicle_type": "afp_fund",
        "currency": "CLP",
        "tax_wrapper": null,
        "liquidity_days": null,
        "is_captive": true,
        "is_sellable": false,
        "can_switch_internal": true,
        "partial_redeemable": false,
        "minimum_trade_amount_clp": null,
        "minimum_residual_amount_clp": null
      },
      "instrument_mix_profile": {
        "reported_current_mix": null,
        "estimated_current_mix": {
          "rv": 0.8,
          "rf": 0.2,
          "cash": 0.0,
          "other": 0.0
        },
        "current_mix_used": {
          "rv": 0.8,
          "rf": 0.2,
          "cash": 0.0,
          "other": 0.0,
          "source_preference": "estimated"
        },
        "reported_current_exposure": null,
        "estimated_current_exposure": {
          "global": 0.75,
          "local": 0.25,
          "hedged": null,
          "unhedged": null
        },
        "current_exposure_used": {
          "global": 0.75,
          "local": 0.25,
          "hedged": null,
          "unhedged": null,
          "source_preference": "estimated"
        },
        "legal_range": {
          "rv_min": 0.4,
          "rv_max": 0.8,
          "rf_min": 0.2,
          "rf_max": 0.6,
          "cash_min": 0.0,
          "cash_max": 0.1
        },
        "historical_used_range": {
          "rv_min": 0.75,
          "rv_max": 0.8,
          "rf_min": 0.2,
          "rf_max": 0.25,
          "observed_window_months": null,
          "observed_from": null,
          "observed_to": null,
          "observation_count": null,
          "estimation_method": "manual_estimate"
        },
        "data_quality": {
          "range_source_type": "manual_estimate",
          "lookthrough_quality": "medium",
          "confidence_score": 0.7,
          "current_mix_quality": "medium",
          "historical_range_quality": "low",
          "current_exposure_quality": "low",
          "legal_range_quality": "high"
        },
        "source_metadata": {
          "current_mix_source": "manual override per user instruction (80/20)",
          "historical_range_source": "manual conservative estimate around 80/20 pending manual verification",
          "legal_range_source": "RÃ©gimen de InversiÃ³n fondos de pensiones",
          "current_exposure_source": "manual estimate 75/25 pending manual verification",
          "last_verified_at": "2026-04-16"
        }
      },
      "portfolio_position": {
        "amount_native": 271116837,
        "amount_native_currency": "CLP",
        "fx_to_clp_used": 1.0,
        "valuation_date": "2026-07-06",
        "amount_clp": 271116837,
        "weight_portfolio": 0.174640079,
        "role": "previsional_cautivo",
        "core_or_satellite": "core",
        "bucket_eligible": false,
        "structural_mix_driver": true,
        "estimated_mix_impact_points": {
          "current_rv_points": 0.139712063,
          "historical_rv_points_min": 0.130980059,
          "historical_rv_points_max": 0.139712063
        }
      },
      "optimizer_metadata": {
        "replaceability_score": 0.05,
        "replacement_constraint": "high",
        "switch_equivalent_candidates": [],
        "same_currency_candidates": [],
        "same_manager_candidates": [],
        "same_tax_wrapper_candidates": [],
        "decision_eligible": true,
        "notes": [
          "PlanVital modeled with manual override 80/20 by user instruction.",
          "Historical used range estimated conservatively at 75/25 to 80/20 pending manual verification.",
          "Post-Fase 1: se corrige metadata de impacto RV para cuadrar con weight_portfolio * current_mix_used.rv."
        ]
      }
    },
    {
      "instrument_master": {
        "instrument_id": "usd_accounts",
        "name": "Cuentas corrientes USD remuneradas",
        "manager": "Bancos varios",
        "series": null,
        "vehicle_type": "cash_account",
        "currency": "USD",
        "tax_wrapper": null,
        "liquidity_days": 0,
        "is_captive": false,
        "is_sellable": true,
        "can_switch_internal": false,
        "partial_redeemable": true,
        "minimum_trade_amount_clp": 0,
        "minimum_residual_amount_clp": 0
      },
      "instrument_mix_profile": {
        "reported_current_mix": null,
        "estimated_current_mix": {
          "rv": 0.0,
          "rf": 1.0,
          "cash": 0.0,
          "other": 0.0
        },
        "current_mix_used": {
          "rv": 0.0,
          "rf": 1.0,
          "cash": 0.0,
          "other": 0.0,
          "source_preference": "estimated"
        },
        "reported_current_exposure": null,
        "estimated_current_exposure": {
          "global": 1.0,
          "local": 0.0,
          "hedged": 0.0,
          "unhedged": 1.0
        },
        "current_exposure_used": {
          "global": 1.0,
          "local": 0.0,
          "hedged": 0.0,
          "unhedged": 1.0,
          "source_preference": "estimated"
        },
        "legal_range": {
          "rv_min": 0.0,
          "rv_max": 0.0,
          "rf_min": 1.0,
          "rf_max": 1.0,
          "cash_min": 0.0,
          "cash_max": 1.0
        },
        "historical_used_range": {
          "rv_min": 0.0,
          "rv_max": 0.0,
          "rf_min": 1.0,
          "rf_max": 1.0,
          "observed_window_months": 1,
          "observed_from": "2026-07-06",
          "observed_to": "2026-07-06",
          "observation_count": 1,
          "estimation_method": "manual_estimate"
        },
        "data_quality": {
          "range_source_type": "manual_estimate",
          "lookthrough_quality": "high",
          "confidence_score": 0.98,
          "current_mix_quality": "high",
          "historical_range_quality": "high",
          "current_exposure_quality": "high",
          "legal_range_quality": "high"
        },
        "source_metadata": {
          "current_mix_source": "user provided",
          "historical_range_source": "cash account assumption",
          "legal_range_source": "cash account assumption",
          "current_exposure_source": "USD cash",
          "last_verified_at": "2026-07-06"
        }
      },
      "portfolio_position": {
        "amount_native": 92742,
        "amount_native_currency": "USD",
        "fx_to_clp_used": 921.74,
        "valuation_date": "2026-07-06",
        "amount_clp": 85484011,
        "weight_portfolio": 0.055064579,
        "role": "liquidity",
        "core_or_satellite": "core",
        "bucket_eligible": true,
        "structural_mix_driver": true,
        "estimated_mix_impact_points": {
          "current_rv_points": 0.0,
          "historical_rv_points_min": 0.0,
          "historical_rv_points_max": 0.0
        }
      },
      "optimizer_metadata": {
        "replaceability_score": 0.98,
        "replacement_constraint": "low",
        "switch_equivalent_candidates": [
          "sura_money_market_usd",
          "bgf_usd_short_duration"
        ],
        "same_currency_candidates": [
          "sura_money_market_usd",
          "bgf_usd_short_duration"
        ],
        "same_manager_candidates": [],
        "same_tax_wrapper_candidates": [],
        "decision_eligible": true,
        "notes": [
          "Saldo lÃ­quido, remunerado al 5.8% anual segÃºn dato del usuario.",
          "Post-Fase 1: CLP equivalente actualizado para mix estructural; Aurum sigue gobernando capital econÃ³mico canÃ³nico."
        ]
      }
    },
    {
      "instrument_master": {
        "instrument_id": "bgf_usd_short_duration",
        "name": "BGF US Dollar Short Duration",
        "manager": "BlackRock",
        "series": null,
        "vehicle_type": "offshore_fund",
        "currency": "USD",
        "tax_wrapper": null,
        "liquidity_days": null,
        "is_captive": false,
        "is_sellable": true,
        "can_switch_internal": false,
        "partial_redeemable": true,
        "minimum_trade_amount_clp": null,
        "minimum_residual_amount_clp": null
      },
      "instrument_mix_profile": {
        "reported_current_mix": null,
        "estimated_current_mix": {
          "rv": 0.0,
          "rf": 1.0,
          "cash": 0.0,
          "other": 0.0
        },
        "current_mix_used": {
          "rv": 0.0,
          "rf": 1.0,
          "cash": 0.0,
          "other": 0.0,
          "source_preference": "estimated"
        },
        "reported_current_exposure": null,
        "estimated_current_exposure": {
          "global": 1.0,
          "local": 0.0,
          "hedged": 0.0,
          "unhedged": 1.0
        },
        "current_exposure_used": {
          "global": 1.0,
          "local": 0.0,
          "hedged": 0.0,
          "unhedged": 1.0,
          "source_preference": "estimated"
        },
        "legal_range": {
          "rv_min": 0.0,
          "rv_max": 0.0,
          "rf_min": 0.8,
          "rf_max": 1.0,
          "cash_min": 0.0,
          "cash_max": 0.2
        },
        "historical_used_range": {
          "rv_min": 0.0,
          "rv_max": 0.0,
          "rf_min": 0.95,
          "rf_max": 1.0,
          "observed_window_months": 12,
          "observed_from": "2025-01-01",
          "observed_to": "2025-12-31",
          "observation_count": 1,
          "estimation_method": "manager_report"
        },
        "data_quality": {
          "range_source_type": "manager_report",
          "lookthrough_quality": "high",
          "confidence_score": 0.9,
          "current_mix_quality": "high",
          "historical_range_quality": "medium",
          "current_exposure_quality": "high",
          "legal_range_quality": "high"
        },
        "source_metadata": {
          "current_mix_source": "BlackRock factsheet/policy",
          "historical_range_source": "short duration bond policy assumption",
          "legal_range_source": "BlackRock policy at least 80% in fixed income and money market",
          "current_exposure_source": "USD fixed income",
          "last_verified_at": "2026-04-16"
        }
      },
      "portfolio_position": {
        "amount_native": 58317.66,
        "amount_native_currency": "USD",
        "fx_to_clp_used": 921.74,
        "valuation_date": "2026-07-06",
        "amount_clp": 53753718,
        "weight_portfolio": 0.034625491,
        "role": "defensive",
        "core_or_satellite": "core",
        "bucket_eligible": true,
        "structural_mix_driver": true,
        "estimated_mix_impact_points": {
          "current_rv_points": 0.0,
          "historical_rv_points_min": 0.0,
          "historical_rv_points_max": 0.0
        }
      },
      "optimizer_metadata": {
        "replaceability_score": 0.9,
        "replacement_constraint": "low",
        "switch_equivalent_candidates": [
          "usd_accounts",
          "sura_money_market_usd"
        ],
        "same_currency_candidates": [
          "usd_accounts",
          "sura_money_market_usd"
        ],
        "same_manager_candidates": [],
        "same_tax_wrapper_candidates": [],
        "decision_eligible": true,
        "notes": [
          "Post-Fase 1: CLP equivalente actualizado para mix estructural; amount_native USD es aproximado segÃºn fx_to_clp_used."
        ]
      }
    },
    {
      "instrument_master": {
        "instrument_id": "sura_money_market_usd",
        "name": "SURA Money Market DÃ³lar",
        "manager": "SURA",
        "series": null,
        "vehicle_type": "fondo_mutuo",
        "currency": "USD",
        "tax_wrapper": null,
        "liquidity_days": 10,
        "is_captive": false,
        "is_sellable": true,
        "can_switch_internal": true,
        "partial_redeemable": true,
        "minimum_trade_amount_clp": null,
        "minimum_residual_amount_clp": null
      },
      "instrument_mix_profile": {
        "reported_current_mix": {
          "rv": 0.0,
          "rf": 0.9977,
          "cash": 0.0,
          "other": 0.0023
        },
        "estimated_current_mix": null,
        "current_mix_used": {
          "rv": 0.0,
          "rf": 0.9977,
          "cash": 0.0,
          "other": 0.0023,
          "source_preference": "reported"
        },
        "reported_current_exposure": null,
        "estimated_current_exposure": {
          "global": 1.0,
          "local": 0.0,
          "hedged": 0.0,
          "unhedged": 1.0
        },
        "current_exposure_used": {
          "global": 1.0,
          "local": 0.0,
          "hedged": 0.0,
          "unhedged": 1.0,
          "source_preference": "estimated"
        },
        "legal_range": {
          "rv_min": 0.0,
          "rv_max": 0.0,
          "rf_min": 0.95,
          "rf_max": 1.0,
          "cash_min": 0.0,
          "cash_max": 0.1
        },
        "historical_used_range": {
          "rv_min": 0.0,
          "rv_max": 0.0,
          "rf_min": 0.998,
          "rf_max": 1.0,
          "observed_window_months": 12,
          "observed_from": "2025-01-01",
          "observed_to": "2025-12-31",
          "observation_count": 1,
          "estimation_method": "reported_lookthrough"
        },
        "data_quality": {
          "range_source_type": "reported_lookthrough",
          "lookthrough_quality": "high",
          "confidence_score": 0.92,
          "current_mix_quality": "high",
          "historical_range_quality": "medium",
          "current_exposure_quality": "high",
          "legal_range_quality": "high"
        },
        "source_metadata": {
          "current_mix_source": "SURA Money Market DÃ³lar latest available composition",
          "historical_range_source": "money market operational assumption",
          "legal_range_source": "money market debt/liquidity assumption",
          "current_exposure_source": "USD money market",
          "last_verified_at": "2026-04-16"
        }
      },
      "portfolio_position": {
        "amount_native": 17802.06,
        "amount_native_currency": "USD",
        "fx_to_clp_used": 921.74,
        "valuation_date": "2026-07-06",
        "amount_clp": 16408873,
        "weight_portfolio": 0.010569786,
        "role": "liquidity",
        "core_or_satellite": "core",
        "bucket_eligible": true,
        "structural_mix_driver": true,
        "estimated_mix_impact_points": {
          "current_rv_points": 0.0,
          "historical_rv_points_min": 0.0,
          "historical_rv_points_max": 0.0
        }
      },
      "optimizer_metadata": {
        "replaceability_score": 0.94,
        "replacement_constraint": "low",
        "switch_equivalent_candidates": [
          "usd_accounts",
          "bgf_usd_short_duration"
        ],
        "same_currency_candidates": [
          "usd_accounts",
          "bgf_usd_short_duration"
        ],
        "same_manager_candidates": [
          "sura_renta_bonos_chile",
          "sura_renta_local_uf"
        ],
        "same_tax_wrapper_candidates": [],
        "decision_eligible": true,
        "notes": [
          "Post-Fase 1: CLP equivalente actualizado para mix estructural; amount_native USD es aproximado segÃºn fx_to_clp_used."
        ]
      }
    }
  ]
}`;
