import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolveAurumEurUsdForMidas } from '../domain/model/operativeFx';

const source = readFileSync(new URL('./SimulationPage.tsx', import.meta.url), 'utf8');
const appSource = readFileSync(new URL('../App.tsx', import.meta.url), 'utf8');
const adaptersSource = readFileSync(new URL('../integrations/aurum/adapters.ts', import.meta.url), 'utf8');

const converted = resolveAurumEurUsdForMidas(0.86);
assert.equal(converted.valid, true);
assert.equal(converted.sourceUsdEur, 0.86);
assert(Math.abs((converted.eurUsdForMidas ?? 0) - (1 / 0.86)) < 1e-12);
assert.equal(resolveAurumEurUsdForMidas(0).valid, false);
assert.equal(resolveAurumEurUsdForMidas(-0.86).valid, false);
assert.equal(resolveAurumEurUsdForMidas(1.4).eurUsdForMidas, null);

assert(source.includes('Patrimonio total Aurum'));
assert(source.includes('Patrimonio considerado por MIDAS'));
assert(source.includes('Ver desglose patrimonial'));
assert(source.includes('Capital inicial del motor'));
assert(source.includes('Capital de riesgo detectado'));
assert(source.includes('Capital de riesgo incluido en esta corrida'));
assert(source.includes('Capital no usado por esta simulación'));
assert(source.includes('Respaldo habilitado.'));
assert(source.includes('No se usa como respaldo.'));
assert(source.includes('Habilitado.'));
assert(source.includes('No entra.'));
assert(source.includes('USD/CLP aplicado'));
assert(source.includes('EUR/USD aplicado'));
assert(source.includes('Aurum current'));
assert(source.includes('Snapshot Aurum no aplicado'));
assert(source.includes('Fuente de datos aplicada'));
assert(source.includes('dataSourceStatusLabel'));
assert(source.includes('dataSourceTone'));
assert(source.includes('EUR/USD no validado contra Aurum; usando valor estructural del modelo.'));
assert(source.includes('Ver detalle técnico'));
assert(source.includes('Valor fuente Aurum'));
assert(source.includes('USD/EUR'));
assert(source.includes('Transformación aplicada: 1 /'));
assert(source.includes('Monte Carlo'));
assert(!source.includes('Capital riesgo motor'));
assert(!source.includes('Aurum: Modelo base local (sin aplicar snapshot Aurum)'));
assert(!source.includes('Capital fuera del motor'));
assert(appSource.includes('setAurumFxSpotUsdEur'));
assert(appSource.includes('resolveAurumEurUsdForMidas'));
assert(appSource.includes('usdEurFixed: targetEurUsdForMidas'));
assert(appSource.includes('setAurumFxSourceUsdEur'));
assert(adaptersSource.includes('resolveAurumEurUsdForMidas(fxReference.usdEur).eurUsdForMidas'));

const decisionStart = source.indexOf('Barra de decisión');
const decisionEnd = source.indexOf('Ver desglose patrimonial');
assert(decisionStart !== -1 && decisionEnd !== -1 && decisionEnd > decisionStart);
const decisionSlice = source.slice(decisionStart, decisionEnd);
const idxPatrimonioAurum = decisionSlice.indexOf('Patrimonio total Aurum');
const idxDepto = decisionSlice.indexOf('Depto');
const idxRiesgo = decisionSlice.indexOf('Capital de riesgo');
const idxPatrimonioMidas = decisionSlice.indexOf('Patrimonio considerado por MIDAS');
const idxEscenario = decisionSlice.indexOf('Escenario');
const idxMonteCarlo = decisionSlice.indexOf('Monte Carlo');
assert(idxPatrimonioAurum !== -1 && idxDepto !== -1 && idxRiesgo !== -1 && idxPatrimonioMidas !== -1 && idxEscenario !== -1 && idxMonteCarlo !== -1);
assert(idxPatrimonioAurum < idxDepto);
assert(idxDepto < idxRiesgo);
assert(idxRiesgo < idxPatrimonioMidas);
assert(idxPatrimonioMidas < idxEscenario);
assert(idxEscenario < idxMonteCarlo);

console.log('SimulationPage tests passed');
