import assert from 'node:assert/strict';
import { buildM8ReplayTrace } from './m8ReplayTrace';

const base = () => buildM8ReplayTrace({
  paramsLabel: 'Desde Aurum · abril 2026',
  effectiveEngineInput: {
    years: 40,
    n_paths: 3000,
    seed: 42,
    simulation_frequency: 'monthly',
    use_real_terms: true,
    simulation_base_month: '2026-04',
    capital_initial_clp: 1_530_974_913,
    capital_source: 'aurum',
    capital_source_label: 'Aurum',
    risk_capital_clp: 294_112_400,
    risk_capital_policy: 'reserve_on_top',
    risk_capital_btc_driver: 'btc_like_realista_e',
    portfolio_mix: {
      eq_global: 0.35,
      eq_chile: 0.15,
      fi_global: 0.30,
      fi_chile: 0.20,
    },
    phase1MonthlyClp: 6_000_000,
    phase2MonthlyClp: 6_000_000,
    phase3MonthlyClp: 4_000_000,
    phase4MonthlyClp: 3_000_000,
    phase1EndYear: 10,
    phase2EndYear: 20,
    phase3EndYear: 30,
    generator_type: 'student_t',
    generator_params: { df: 7, block_length: 12 },
    bucket: { bucket_mode: 'operational_simple', bucket_months: 24 },
    cuts: { dd15: -0.15, dd25: -0.25, soft: -0.1, hard: -0.2 },
    house: { include_house: true, sale_delay_months: 12 },
    future_events: [{ id: 'salary-2030', type: 'inflow', effective_month: 48, amount: 100_000_000, currency: 'CLP' }],
  },
  effectiveEngineInputFingerprint: 'fnv1a-effective',
  m8Fingerprint: 'fnv1a-m8',
  diagnosticFingerprint: 'fnv1a-diagnostic',
  simulationConfigSource: 'cloud',
  simulationConfigSavedAt: '2026-05-07T10:01:00.000Z',
  simulationConfigHash: 'cfg-abc',
  simulationConfigDiagnostics: {
    path: 'users/uid-123/midas_config/simulationActiveV1',
    previousGlobalConfigPath: 'midas_config/simulationActiveV1',
    projectId: 'test-project',
    configured: true,
    authUid: 'uid-123',
    authEmail: 'user@example.com',
    authProvider: 'google.com',
    isAnonymous: false,
    loginRequired: false,
    isCanonicalUserSession: true,
    readStatus: 'loaded',
    errorMessage: null,
    exists: true,
    updatedAt: '2026-05-07T10:01:30.000Z',
    activeHash: 'cfg-abc',
    activeSavedAt: '2026-05-07T10:01:00.000Z',
    activeParamsJsonExists: true,
    activeSpendingPhasesExists: true,
    activeSeedExists: true,
    activeNSimExists: true,
    activeBucketMonthsExists: true,
    legacyGlobalReadStatus: null,
    legacyGlobalErrorMessage: null,
    legacyGlobalExists: null,
    legacyGlobalHash: null,
    missingFields: [],
  },
  weightsSourceMode: 'instrument-universe',
  universeSourceOrigin: 'firestore',
  instrumentUniverseSavedAt: '2026-05-07T10:02:00.000Z',
  instrumentUniverseHash: 'u-abc',
  instrumentUniverseDiagnostics: {
    cloudReadStatus: 'loaded',
  },
  aurumSnapshotMonth: '2026-04',
  aurumSnapshotLabel: '2026-04 cierre',
  aurumSnapshotPublishedAt: '2026-05-07T10:00:00.000Z',
  aurumSnapshotSignature: 'snap-abc',
  runtimeDiagnostics: {
    canonicalInputReady: true,
    canonicalInputPendingSource: null,
    canonicalInputBlockedReason: null,
    canonicalInputStatusMessage: null,
    simulationRunStatus: 'completed',
    resultMetricsAvailable: true,
  },
  fieldSources: {
    capitalInitialClp: 'aurum_snapshot_cloud',
    instrumentUniverse: 'cloud',
  },
  capitalDerivationDiagnostics: {
    manualAdjustmentsCount: 0,
    manualLocalAdjustmentsAffectEngine: false,
  },
  warnings: [],
});

(() => {
  const first = base();
  const second = base();
  assert.deepEqual(first, second, 'same effective input and metadata must produce the same replay trace');
})();

(() => {
  const traceA = base();
  const traceB = buildM8ReplayTrace({
    paramsLabel: 'Desde Aurum · abril 2026',
    effectiveEngineInput: {
      years: 40,
      n_paths: 3000,
      seed: 42,
      simulation_frequency: 'monthly',
      use_real_terms: true,
      simulation_base_month: '2026-04',
      capital_initial_clp: 1_530_974_913,
      capital_source: 'aurum',
      capital_source_label: 'Aurum',
      risk_capital_clp: 294_112_400,
      risk_capital_policy: 'reserve_on_top',
      risk_capital_btc_driver: 'btc_like_realista_e',
      portfolio_mix: {
        eq_global: 0.35,
        eq_chile: 0.15,
        fi_global: 0.30,
        fi_chile: 0.20,
      },
      phase1MonthlyClp: 6_000_000,
      phase2MonthlyClp: 6_000_000,
      phase3MonthlyClp: 4_000_000,
      phase4MonthlyClp: 3_000_000,
      phase1EndYear: 10,
      phase2EndYear: 20,
      phase3EndYear: 30,
      generator_type: 'student_t',
      generator_params: { df: 7, block_length: 12 },
      bucket: { bucket_mode: 'operational_simple', bucket_months: 24 },
      cuts: { dd15: -0.15, dd25: -0.25, soft: -0.1, hard: -0.2 },
      house: { include_house: true, sale_delay_months: 12 },
      future_events: [{ id: 'salary-2030', type: 'inflow', effective_month: 48, amount: 100_000_000, currency: 'CLP' }],
    },
    effectiveEngineInputFingerprint: 'fnv1a-effective',
    m8Fingerprint: 'fnv1a-m8',
    diagnosticFingerprint: 'fnv1a-diagnostic',
    simulationConfigSource: 'cloud',
    simulationConfigSavedAt: '2026-05-07T10:01:00.000Z',
    simulationConfigHash: 'cfg-abc',
    simulationConfigDiagnostics: {
      path: 'users/uid-456/midas_config/simulationActiveV1',
      previousGlobalConfigPath: 'midas_config/simulationActiveV1',
      projectId: 'test-project',
      configured: true,
      authUid: 'uid-456',
      authEmail: 'other@example.com',
      authProvider: 'google.com',
      isAnonymous: false,
      loginRequired: false,
      isCanonicalUserSession: true,
      readStatus: 'loaded',
      errorMessage: null,
      exists: true,
      updatedAt: '2026-05-07T10:01:30.000Z',
      activeHash: 'cfg-abc',
      activeSavedAt: '2026-05-07T10:01:00.000Z',
      activeParamsJsonExists: true,
      activeSpendingPhasesExists: true,
      activeSeedExists: true,
      activeNSimExists: true,
      activeBucketMonthsExists: true,
      legacyGlobalReadStatus: null,
      legacyGlobalErrorMessage: null,
      legacyGlobalExists: null,
      legacyGlobalHash: null,
      missingFields: [],
    },
    weightsSourceMode: 'instrument-universe',
    universeSourceOrigin: 'firestore',
    instrumentUniverseSavedAt: '2026-05-07T10:02:00.000Z',
    instrumentUniverseHash: 'u-abc',
    instrumentUniverseDiagnostics: {
      cloudReadStatus: 'loaded',
    },
    aurumSnapshotMonth: '2026-04',
    aurumSnapshotLabel: '2026-04 cierre',
    aurumSnapshotPublishedAt: '2026-05-07T10:00:00.000Z',
    aurumSnapshotSignature: 'snap-abc',
    runtimeDiagnostics: {
      canonicalInputReady: true,
      canonicalInputPendingSource: null,
      canonicalInputBlockedReason: null,
      canonicalInputStatusMessage: null,
      simulationRunStatus: 'completed',
      resultMetricsAvailable: true,
    },
    fieldSources: {
      capitalInitialClp: 'aurum_snapshot_cloud',
      instrumentUniverse: 'cloud',
    },
    capitalDerivationDiagnostics: {
      manualAdjustmentsCount: 2,
      manualLocalAdjustmentsAffectEngine: false,
    },
    warnings: ['Hay ajustes manuales locales fuera del modo canónico: no cambian el input M8 comparable.'],
  });
  assert.deepEqual(traceA.canonicalInput, traceB.canonicalInput, 'local-only differences must not change canonical input');
  assert.equal(
    traceA.fingerprints.effectiveEngineInputFingerprint,
    traceB.fingerprints.effectiveEngineInputFingerprint,
    'two devices with different local state must keep the same canonical effective fingerprint',
  );
})();

(() => {
  const blocked = buildM8ReplayTrace({
    paramsLabel: 'Desde Aurum · abril 2026',
    effectiveEngineInput: {
      years: 40,
      n_paths: 3000,
      seed: 42,
      simulation_frequency: 'monthly',
      use_real_terms: true,
      simulation_base_month: '2026-04',
      capital_initial_clp: 1_530_974_913,
      capital_source: 'aurum',
      capital_source_label: 'Aurum',
      portfolio_mix: {
        eq_global: 0.35,
        eq_chile: 0.15,
        fi_global: 0.30,
        fi_chile: 0.20,
      },
      phase1MonthlyClp: 6_000_000,
      phase2MonthlyClp: 6_000_000,
      phase3MonthlyClp: 4_000_000,
      phase4MonthlyClp: 3_000_000,
      phase1EndYear: 10,
      phase2EndYear: 20,
      phase3EndYear: 30,
      generator_type: 'student_t',
      generator_params: { df: 7, block_length: 12 },
      bucket: { bucket_mode: 'operational_simple', bucket_months: 24 },
      cuts: { dd15: -0.15, dd25: -0.25, soft: -0.1, hard: -0.2 },
      future_events: [],
    },
    effectiveEngineInputFingerprint: 'fnv1a-effective',
    m8Fingerprint: 'fnv1a-m8',
    diagnosticFingerprint: 'fnv1a-diagnostic',
    simulationConfigSource: 'fallback',
    simulationConfigHash: null,
    simulationConfigSavedAt: null,
    simulationConfigDiagnostics: {
      path: 'users/uid-123/midas_config/simulationActiveV1',
      previousGlobalConfigPath: 'midas_config/simulationActiveV1',
      projectId: 'test-project',
      configured: true,
      authUid: 'uid-123',
      authEmail: 'user@example.com',
      authProvider: 'google.com',
      isAnonymous: false,
      loginRequired: false,
      isCanonicalUserSession: true,
      readStatus: 'missing',
      errorMessage: null,
      exists: false,
      updatedAt: null,
      activeHash: null,
      activeSavedAt: null,
      activeParamsJsonExists: false,
      activeSpendingPhasesExists: false,
      activeSeedExists: false,
      activeNSimExists: false,
      activeBucketMonthsExists: false,
      legacyGlobalReadStatus: null,
      legacyGlobalErrorMessage: null,
      legacyGlobalExists: null,
      legacyGlobalHash: null,
      missingFields: ['activeParamsJsonExists'],
    },
    weightsSourceMode: 'instrument-universe',
    universeSourceOrigin: 'firestore',
    instrumentUniverseSavedAt: '2026-05-07T10:02:00.000Z',
    instrumentUniverseHash: 'u-abc',
    instrumentUniverseDiagnostics: {
      cloudReadStatus: 'loaded',
    },
    aurumSnapshotMonth: '2026-04',
    aurumSnapshotLabel: '2026-04 cierre',
    aurumSnapshotPublishedAt: '2026-05-07T10:00:00.000Z',
    aurumSnapshotSignature: 'snap-abc',
    runtimeDiagnostics: {
      canonicalInputReady: false,
      canonicalInputPendingSource: 'config cloud',
      canonicalInputBlockedReason: 'config_missing',
      canonicalInputStatusMessage: 'Falta la config cloud oficial de simulación.',
      simulationRunStatus: 'blocked',
      resultMetricsAvailable: false,
    },
    warnings: ['Config cloud no existe: usando fallback local no comparable cross-device.'],
  });
  assert.equal(blocked.readiness.state, 'blocked');
  assert.equal(blocked.readiness.pendingSource, 'config cloud');
  assert.equal(blocked.readiness.simulated, false);
})();

(() => {
  const trace = buildM8ReplayTrace({
    paramsLabel: 'Desde Aurum · abril 2026',
    effectiveEngineInput: {
      years: 40,
      n_paths: 3000,
      seed: 42,
      simulation_frequency: 'monthly',
      use_real_terms: true,
      simulation_base_month: '2026-04',
      capital_initial_clp: 1_530_974_913,
      capital_source: 'aurum',
      capital_source_label: 'Aurum',
      portfolio_mix: {
        eq_global: 0.35,
        eq_chile: 0.15,
        fi_global: 0.30,
        fi_chile: 0.20,
      },
      phase1MonthlyClp: 6_000_000,
      phase2MonthlyClp: 6_000_000,
      phase3MonthlyClp: 4_000_000,
      phase4MonthlyClp: 3_000_000,
      phase1EndYear: 10,
      phase2EndYear: 20,
      phase3EndYear: 30,
      generator_type: 'student_t',
      generator_params: { df: 7, block_length: 12 },
      bucket: { bucket_mode: 'operational_simple', bucket_months: 24 },
      cuts: { dd15: -0.15, dd25: -0.25, soft: -0.1, hard: -0.2 },
      future_events: [],
    },
    effectiveEngineInputFingerprint: 'fnv1a-effective',
    m8Fingerprint: 'fnv1a-m8',
    diagnosticFingerprint: 'fnv1a-diagnostic',
    simulationConfigSource: 'cloud',
    simulationConfigSavedAt: '2026-05-07T10:01:00.000Z',
    simulationConfigHash: 'cfg-abc',
    simulationConfigDiagnostics: {
      path: 'users/uid-123/midas_config/simulationActiveV1',
      previousGlobalConfigPath: 'midas_config/simulationActiveV1',
      projectId: 'test-project',
      configured: true,
      authUid: 'uid-123',
      authEmail: 'user@example.com',
      authProvider: 'google.com',
      isAnonymous: false,
      loginRequired: false,
      isCanonicalUserSession: true,
      readStatus: 'loaded',
      errorMessage: null,
      exists: true,
      updatedAt: '2026-05-07T10:01:30.000Z',
      activeHash: 'cfg-abc',
      activeSavedAt: '2026-05-07T10:01:00.000Z',
      activeParamsJsonExists: true,
      activeSpendingPhasesExists: true,
      activeSeedExists: true,
      activeNSimExists: true,
      activeBucketMonthsExists: true,
      legacyGlobalReadStatus: null,
      legacyGlobalErrorMessage: null,
      legacyGlobalExists: null,
      legacyGlobalHash: null,
      missingFields: [],
    },
    weightsSourceMode: 'instrument-universe',
    universeSourceOrigin: 'firestore',
    instrumentUniverseSavedAt: '2026-05-07T10:02:00.000Z',
    instrumentUniverseHash: 'u-abc',
    instrumentUniverseDiagnostics: {
      cloudReadStatus: 'loaded',
    },
    aurumSnapshotMonth: '2026-04',
    aurumSnapshotLabel: '2026-04 cierre',
    aurumSnapshotPublishedAt: '2026-05-07T10:00:00.000Z',
    aurumSnapshotSignature: 'snap-abc',
    runtimeDiagnostics: {
      canonicalInputReady: true,
      simulationRunStatus: 'completed',
      resultMetricsAvailable: true,
    },
    capitalDerivationDiagnostics: {
      manualAdjustmentsCount: 1,
      manualLocalAdjustmentsAffectEngine: false,
    },
    warnings: ['Hay ajustes manuales locales fuera del modo canónico: no cambian el input M8 comparable.'],
  });
  assert.ok(trace.warnings.some((warning) => warning.includes('modo canónico')));
  assert.equal(trace.canonicalInput.effectiveCapitalInitialClp, 1_530_974_913);
})();

(() => {
  const trace = base();
  const serialized = JSON.stringify(trace);
  assert(!serialized.includes('user@example.com'));
  assert(!serialized.includes('uid-123'));
  assert.equal(trace.canonicalInput.spendingPhases.F1, 6_000_000);
  assert.deepEqual(trace.canonicalInput.portfolioMix, {
    eq_global: 0.35,
    eq_chile: 0.15,
    fi_global: 0.30,
    fi_chile: 0.20,
  });
})();

console.log('m8ReplayTrace tests passed');
